OK

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -50,8 +50,12 @@ function install_rlwrap() {
         LDFLAGS="-L$(brew --prefix readline)/lib" \
           ./configure --prefix="$install_path" >/dev/null || fail "Could not configure"
         ;;
-      linux*) ./configure --prefix="$install_path" || fail "Could not configure" ;;
-      *) fail "Unsupported platform..." ;;
+      linux*)
+        ./configure --prefix="$install_path" || fail "Could not configure"
+        ;;
+      *)
+        fail "Unsupported platform..."
+        ;;
     esac
 
     echo "∗ Compiling..."
