OK

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -43,7 +43,7 @@ function install_rlwrap() {
     cd "$distination"
 
     echo "∗ Recreating configure file..."
-    autoreconf --install || fail "Could not recreate configure file"
+    autoreconf --install 2>/dev/null || fail "Could not recreate configure file"
 
     echo "∗ Configuring..."
     case "$OSTYPE" in
